name: apply
on:
  workflow_dispatch:
    inputs:
      plan_run_id:
        description: "Run ID of the successful 'plan' workflow to fetch the reviewed tfplan artifact"
        required: true

permissions:
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      TF_IN_AUTOMATION: "1"
      TF_INPUT: "0"
    steps:
      - uses: actions/checkout@v4

      # Download the reviewed plan artifact from the specified 'plan' run
      - name: Download plan artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          run_id: ${{ inputs.plan_run_id }}
          name: tfplan
          path: .

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
          terraform_wrapper: false

      - name: Write OCI key (PEM) to runner
        run: |
          umask 077
          printf '%s' "${{ secrets.OCI_PRIVATE_KEY_PEM }}" > "$RUNNER_TEMP/oci_api_key.pem"

      - name: Write SSH public key to runner
        run: |
          umask 077
          printf '%s' "${{ secrets.SSH_PUBLIC_KEY }}" > "$RUNNER_TEMP/ssh_public_key.pub"

      - name: Create backend.oci.hcl
        run: |
          cat > backend.oci.hcl <<'HCL'
          bucket     = "${{ secrets.TF_STATE_BUCKET }}"
          namespace  = "${{ secrets.OS_NAMESPACE }}"
          region     = "${{ secrets.OCI_REGION }}"
          key        = "${{ secrets.TF_STATE_KEY }}"
          workspace_key_prefix = "envs/"
          HCL

      - name: Terraform init (root)
        env:
          TF_VAR_tenancy_ocid:         ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid:            ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint:          ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_region:               ${{ secrets.OCI_REGION }}
          TF_VAR_private_key_path:     ${{ runner.temp }}/oci_api_key.pem
          TF_VAR_compartment_ocid:     ${{ secrets.COMPARTMENT_OCID }}
          TF_VAR_availability_domain:  ${{ secrets.AVAILABILITY_DOMAIN }}
          TF_VAR_os_image_id:          ${{ secrets.OS_IMAGE_ID }}
          TF_VAR_cluster_name:         ${{ secrets.CLUSTER_NAME }}
          TF_VAR_public_key_path:      ${{ runner.temp }}/ssh_public_key.pub
          TF_VAR_admin_cidr:           ${{ secrets.ADMIN_CIDR }}
        run: terraform init -backend-config=backend.oci.hcl

      - name: Terraform apply reviewed plan
        env:
          TF_VAR_tenancy_ocid:         ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid:            ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint:          ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_region:               ${{ secrets.OCI_REGION }}
          TF_VAR_private_key_path:     ${{ runner.temp }}/oci_api_key.pem
          TF_VAR_compartment_ocid:     ${{ secrets.COMPARTMENT_OCID }}
          TF_VAR_availability_domain:  ${{ secrets.AVAILABILITY_DOMAIN }}
          TF_VAR_os_image_id:          ${{ secrets.OS_IMAGE_ID }}
          TF_VAR_cluster_name:         ${{ secrets.CLUSTER_NAME }}
          TF_VAR_public_key_path:      ${{ runner.temp }}/ssh_public_key.pub
          TF_VAR_admin_cidr:           ${{ secrets.ADMIN_CIDR }}
        run: terraform apply -auto-approve tfplan
