name: apply
on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      TF_IN_AUTOMATION: "1"
      TF_INPUT: "0"
      # Keep these in sync with plan.yml
      TF_VAR_tenancy_ocid:        ${{ secrets.OCI_TENANCY_OCID }}
      TF_VAR_user_ocid:           ${{ secrets.OCI_USER_OCID }}
      TF_VAR_fingerprint:         ${{ secrets.OCI_FINGERPRINT }}
      TF_VAR_region:              ${{ secrets.OCI_REGION }}
      TF_VAR_private_key_pem:     ${{ secrets.OCI_PRIVATE_KEY_PEM }}
      TF_VAR_compartment_ocid:    ${{ secrets.COMPARTMENT_OCID }}
      TF_VAR_availability_domain: ${{ secrets.AVAILABILITY_DOMAIN }}
      TF_VAR_os_image_id:         ${{ secrets.OS_IMAGE_ID }}
      TF_VAR_cluster_name:        ${{ secrets.CLUSTER_NAME }}
      TF_VAR_admin_cidr:          ${{ secrets.ADMIN_CIDR }}
      TF_VAR_public_key_content:  ${{ secrets.SSH_PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v4

      # NOTE: this downloads from the SAME workflow run that uploaded it.
      # If you trigger apply in a separate run, this step won’t find the artifact.
      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Create backend.oci.hcl
        run: |
          cat > backend.oci.hcl <<'HCL'
          tenancy_ocid     = "${{ secrets.OCI_TENANCY_OCID }}"
          user_ocid        = "${{ secrets.OCI_USER_OCID }}"
          fingerprint      = "${{ secrets.OCI_FINGERPRINT }}"
          private_key_pem  = "${{ secrets.OCI_PRIVATE_KEY_PEM }}"
          bucket           = "${{ secrets.TF_STATE_BUCKET }}"
          namespace        = "${{ secrets.OS_NAMESPACE }}"
          region           = "${{ secrets.OCI_REGION }}"
          key              = "${{ secrets.TF_STATE_KEY }}"
          workspace_key_prefix = "envs/"
          HCL

      - name: Terraform init (match plan versions)
        run: terraform init -backend-config=backend.oci.hcl
      - name: Terraform plan (in apply)
        run: terraform plan -out=tfplan
      - name: Terraform apply (saved plan)
        run: terraform apply -input=false tfplan
