name: destroy
on:
  workflow_dispatch: {}

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      TF_IN_AUTOMATION: "1"
      TF_INPUT: "0"
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Write OCI key (PEM) to runner
        run: |
          umask 077
          echo "${{ secrets.OCI_PRIVATE_KEY_PEM }}" > "$RUNNER_TEMP/oci_api_key.pem"

      - name: Create backend.oci.hcl
        run: |
          cat > backend.oci.hcl <<'HCL'
          bucket    = "${{ secrets.TF_STATE_BUCKET }}"
          namespace = "${{ secrets.OS_NAMESPACE }}"
          region    = "${{ secrets.OCI_REGION }}"
          key       = "${{ secrets.TF_STATE_KEY }}"
          workspace_key_prefix = "envs/"
          HCL

      - name: Terraform init (root)
        env:
          TF_VAR_tenancy_ocid:     ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid:        ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint:      ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_region:           ${{ secrets.OCI_REGION }}
          TF_VAR_private_key_path: ${{ runner.temp }}/oci_api_key.pem
        run: terraform init -backend-config=backend.oci.hcl

      - name: Terraform destroy
        env:
          TF_VAR_tenancy_ocid:     ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid:        ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint:      ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_region:           ${{ secrets.OCI_REGION }}
          TF_VAR_private_key_path: ${{ runner.temp }}/oci_api_key.pem
        run: terraform destroy -auto-approve
