name: plan
on:
  workflow_dispatch: {}
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      TF_IN_AUTOMATION: "1"
      TF_INPUT: "0"
    steps:
      - uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
          terraform_wrapper: false

      - name: Write OCI key (PEM) to runner
        run: |
          umask 077
          printf '%s' "${{ secrets.OCI_PRIVATE_KEY_PEM }}" > "$RUNNER_TEMP/oci_api_key.pem"

      - name: Write SSH public key to runner
        run: |
          umask 077
          printf '%s' "${{ secrets.SSH_PUBLIC_KEY }}" > "$RUNNER_TEMP/ssh_public_key.pub"

      - name: Create backend.oci.hcl
        run: |
          cat > backend.oci.hcl <<'HCL'
          bucket     = "${{ secrets.TF_STATE_BUCKET }}"
          namespace  = "${{ secrets.OS_NAMESPACE }}"
          region     = "${{ secrets.OCI_REGION }}"
          key        = "${{ secrets.TF_STATE_KEY }}"
          workspace_key_prefix = "envs/"
          HCL

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform init (root)
        env:
          TF_VAR_tenancy_ocid:         ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid:            ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint:          ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_region:               ${{ secrets.OCI_REGION }}
          TF_VAR_private_key_path:     ${{ runner.temp }}/oci_api_key.pem
          TF_VAR_compartment_ocid:     ${{ secrets.COMPARTMENT_OCID }}
          TF_VAR_availability_domain:  ${{ secrets.AVAILABILITY_DOMAIN }}
          TF_VAR_os_image_id:          ${{ secrets.OS_IMAGE_ID }}
          TF_VAR_cluster_name:         ${{ secrets.CLUSTER_NAME }}
          TF_VAR_public_key_path:      ${{ runner.temp }}/ssh_public_key.pub
          TF_VAR_admin_cidr:           ${{ secrets.ADMIN_CIDR }}
          OCI_TENANCY_OCID:     ${{ secrets.OCI_TENANCY_OCID }}
          OCI_USER_OCID:        ${{ secrets.OCI_USER_OCID }}
          OCI_FINGERPRINT:      ${{ secrets.OCI_FINGERPRINT }}
          OCI_REGION:           ${{ secrets.OCI_REGION }}
          OCI_PRIVATE_KEY_PATH: ${{ runner.temp }}/oci_api_key.pem
        run: terraform init -backend-config=backend.oci.hcl

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        env:
          TF_VAR_tenancy_ocid:         ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid:            ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint:          ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_region:               ${{ secrets.OCI_REGION }}
          TF_VAR_private_key_path:     ${{ runner.temp }}/oci_api_key.pem
          TF_VAR_compartment_ocid:     ${{ secrets.COMPARTMENT_OCID }}
          TF_VAR_availability_domain:  ${{ secrets.AVAILABILITY_DOMAIN }}
          TF_VAR_os_image_id:          ${{ secrets.OS_IMAGE_ID }}
          TF_VAR_cluster_name:         ${{ secrets.CLUSTER_NAME }}
          TF_VAR_public_key_path:      ${{ runner.temp }}/ssh_public_key.pub
          TF_VAR_admin_cidr:           ${{ secrets.ADMIN_CIDR }}
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          OS_NAMESPACE: ${{ secrets.OS_NAMESPACE }}
          TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}
        run: terraform plan -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
          if-no-files-found: error
