name: plan
on:
  workflow_dispatch: {}
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      TF_IN_AUTOMATION: "1"
      TF_INPUT: "0"
    steps:
      - uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          # Using a consistent version across workflows is recommended
          terraform_version: 1.7.5


      - name: Create backend.oci.hcl
        run: |
          cat > backend.oci.hcl <<'HCL'
          bucket    = "${{ secrets.TF_STATE_BUCKET }}"
          namespace = "${{ secrets.OS_NAMESPACE }}"
          region    = "${{ secrets.OCI_REGION }}"
          key       = "${{ secrets.TF_STATE_KEY }}"
          workspace_key_prefix = "envs/"
          HCL

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform init (root)
        env:
          TF_VAR_tenancy_ocid:        ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid:           ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint:         ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_region:              ${{ secrets.OCI_REGION }}
          TF_VAR_private_key_pem:     ${{ secrets.OCI_PRIVATE_KEY_PEM }} # MODIFIED: Pass PEM content directly
          TF_VAR_compartment_ocid:    ${{ secrets.COMPARTMENT_OCID }}
          TF_VAR_availability_domain: ${{ secrets.AVAILABILITY_DOMAIN }}
          TF_VAR_os_image_id:         ${{ secrets.OS_IMAGE_ID }}
          TF_VAR_cluster_name:        ${{ secrets.CLUSTER_NAME }}
          TF_VAR_admin_cidr:          ${{ secrets.ADMIN_CIDR }}
          TF_VAR_public_key_content:  ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform init -backend-config=backend.oci.hcl

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        env:
          # NOTE: Redundant env block can be removed if defined at the job level, but keeping for clarity.
          TF_VAR_tenancy_ocid:        ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid:           ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint:         ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_region:              ${{ secrets.OCI_REGION }}
          TF_VAR_private_key_pem:     ${{ secrets.OCI_PRIVATE_KEY_PEM }} # MODIFIED: Pass PEM content directly
          TF_VAR_compartment_ocid:    ${{ secrets.COMPARTMENT_OCID }}
          TF_VAR_availability_domain: ${{ secrets.AVAILABILITY_DOMAIN }}
          TF_VAR_os_image_id:         ${{ secrets.OS_IMAGE_ID }}
          TF_VAR_cluster_name:        ${{ secrets.CLUSTER_NAME }}
          TF_VAR_public_key_path:     ${{ runner.temp }}/ssh_public_key.pub
          TF_VAR_admin_cidr:          ${{ secrets.ADMIN_CIDR }}
        run: terraform plan -out=tfplan # CORRECTED: Removed invalid CLI variables

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
          if-no-files-found: error